spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.career: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    root: WARN
